In [1]:
# В папке for Python лежит файл с кодом для других стран и штатов

In [14]:
from datetime import date

import holidays

In [15]:
%pylab inline
import pandas as pd
from scipy import stats
import statsmodels.api as sm
import matplotlib.pyplot as plt
import warnings
from itertools import product


import seaborn
from sklearn import preprocessing
from matplotlib.colors import LogNorm
from sklearn.metrics import accuracy_score
from sklearn  import metrics

from sklearn.preprocessing import MinMaxScaler

Populating the interactive namespace from numpy and matplotlib

/Users/aurinko/anaconda/envs/Python2_7_TensorFlow/lib/python2.7/site-packages/IPython/core/magics/pylab.py:161: UserWarning: pylab import has clobbered these variables: ['product']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"

In [16]:
shdf = pd.read_csv('shdf3.csv',',',  dayfirst=True)#, index_col=['Dates'], parse_dates=['Dates'])
#df.columns
shdf.head()

,Dates,Category,PdDistrict,X,Y,year,dayOfyear,hour,Day,Month,Hour,Weekday,year_s,dayOfyear_s,hour_s,Weekday_s,Xs,Ys,DateTime,holiday
0,2015-05-13 23:53:00,WARRANTS,NORTHERN,-122.425892,37.774599,2015,133,23,13,5,23,2,1.0,0.362637,1.0,0.333333,0.590099,0.595198,2015-05-13,0
1,2015-05-13 23:53:00,OTHER OFFENSES,NORTHERN,-122.425892,37.774599,2015,133,23,13,5,23,2,1.0,0.362637,1.0,0.333333,0.590099,0.595198,2015-05-13,0
2,2015-05-13 23:33:00,OTHER OFFENSES,NORTHERN,-122.424363,37.800414,2015,133,23,13,5,23,2,1.0,0.362637,1.0,0.333333,0.600379,0.825497,2015-05-13,0
3,2015-05-13 23:30:00,LARCENY/THEFT,NORTHERN,-122.426995,37.800873,2015,133,23,13,5,23,2,1.0,0.362637,1.0,0.333333,0.582677,0.829586,2015-05-13,0
4,2015-05-13 23:30:00,LARCENY/THEFT,PARK,-122.438738,37.771541,2015,133,23,13,5,23,2,1.0,0.362637,1.0,0.333333,0.503713,0.567923,2015-05-13,0

In [19]:
us_holidays = holidays.UnitedStates() #UnitedStates()  # or holidays.US()

In [20]:
date(2015, 1, 1) in us_holidays  # True

True

In [21]:
date(2015, 1, 2) in us_holidays  # False

False

In [22]:
shdf['holidays'] = shdf.DateTime.map(lambda x: 1 if pd.to_datetime(x) in us_holidays else 0)

In [23]:
shdf.head()

,Dates,Category,PdDistrict,X,Y,year,dayOfyear,hour,Day,Month,...,Weekday,year_s,dayOfyear_s,hour_s,Weekday_s,Xs,Ys,DateTime,holiday,holidays
0,2015-05-13 23:53:00,WARRANTS,NORTHERN,-122.425892,37.774599,2015,133,23,13,5,...,2,1.0,0.362637,1.0,0.333333,0.590099,0.595198,2015-05-13,0,0
1,2015-05-13 23:53:00,OTHER OFFENSES,NORTHERN,-122.425892,37.774599,2015,133,23,13,5,...,2,1.0,0.362637,1.0,0.333333,0.590099,0.595198,2015-05-13,0,0
2,2015-05-13 23:33:00,OTHER OFFENSES,NORTHERN,-122.424363,37.800414,2015,133,23,13,5,...,2,1.0,0.362637,1.0,0.333333,0.600379,0.825497,2015-05-13,0,0
3,2015-05-13 23:30:00,LARCENY/THEFT,NORTHERN,-122.426995,37.800873,2015,133,23,13,5,...,2,1.0,0.362637,1.0,0.333333,0.582677,0.829586,2015-05-13,0,0
4,2015-05-13 23:30:00,LARCENY/THEFT,PARK,-122.438738,37.771541,2015,133,23,13,5,...,2,1.0,0.362637,1.0,0.333333,0.503713,0.567923,2015-05-13,0,0

In [24]:
shdf.tail()

,Dates,Category,PdDistrict,X,Y,year,dayOfyear,hour,Day,Month,...,Weekday,year_s,dayOfyear_s,hour_s,Weekday_s,Xs,Ys,DateTime,holiday,holidays
877977,2003-01-06 00:15:00,ROBBERY,TARAVAL,-122.459033,37.714056,2003,6,0,6,1,...,0,0.0,0.013736,0.0,0.0,0.367231,0.055107,2003-01-06,0,0
877978,2003-01-06 00:01:00,LARCENY/THEFT,INGLESIDE,-122.447364,37.731948,2003,6,0,6,1,...,0,0.0,0.013736,0.0,0.0,0.445706,0.214713,2003-01-06,0,0
877979,2003-01-06 00:01:00,LARCENY/THEFT,SOUTHERN,-122.403390,37.780266,2003,6,0,6,1,...,0,0.0,0.013736,0.0,0.0,0.741414,0.645752,2003-01-06,0,0
877980,2003-01-06 00:01:00,VANDALISM,SOUTHERN,-122.390531,37.780607,2003,6,0,6,1,...,0,0.0,0.013736,0.0,0.0,0.827888,0.648799,2003-01-06,0,0
877981,2003-01-06 00:01:00,FORGERY/COUNTERFEITING,BAYVIEW,-122.394926,37.738212,2003,6,0,6,1,...,0,0.0,0.013736,0.0,0.0,0.798337,0.270593,2003-01-06,0,0

In [25]:
shdf[shdf['holidays'] == 1]

,Dates,Category,PdDistrict,X,Y,year,dayOfyear,hour,Day,Month,...,Weekday,year_s,dayOfyear_s,hour_s,Weekday_s,Xs,Ys,DateTime,holiday,holidays
18357,2015-02-16 23:48:00,DRUG/NARCOTIC,SOUTHERN,-122.403405,37.775421,2015,47,23,16,2,...,0,1.0,0.126374,1.000000,0.0,0.741317,0.602532,2015-02-16,0,1
18358,2015-02-16 23:48:00,OTHER OFFENSES,SOUTHERN,-122.403405,37.775421,2015,47,23,16,2,...,0,1.0,0.126374,1.000000,0.0,0.741317,0.602532,2015-02-16,0,1
18359,2015-02-16 23:30:00,NON-CRIMINAL,INGLESIDE,-122.411730,37.709912,2015,47,23,16,2,...,0,1.0,0.126374,1.000000,0.0,0.685333,0.018134,2015-02-16,0,1
18360,2015-02-16 23:30:00,VANDALISM,CENTRAL,-122.415643,37.807762,2015,47,23,16,2,...,0,1.0,0.126374,1.000000,0.0,0.659020,0.891049,2015-02-16,0,1
18361,2015-02-16 23:30:00,LARCENY/THEFT,NORTHERN,-122.429110,37.769899,2015,47,23,16,2,...,0,1.0,0.126374,1.000000,0.0,0.568456,0.553272,2015-02-16,0,1
18362,2015-02-16 23:30:00,OTHER OFFENSES,TENDERLOIN,-122.413238,37.782843,2015,47,23,16,2,...,0,1.0,0.126374,1.000000,0.0,0.675195,0.668745,2015-02-16,0,1
18363,2015-02-16 23:30:00,VANDALISM,TENDERLOIN,-122.413238,37.782843,2015,47,23,16,2,...,0,1.0,0.126374,1.000000,0.0,0.675195,0.668745,2015-02-16,0,1
18364,2015-02-16 23:30:00,VANDALISM,TENDERLOIN,-122.413238,37.782843,2015,47,23,16,2,...,0,1.0,0.126374,1.000000,0.0,0.675195,0.668745,2015-02-16,0,1
18365,2015-02-16 23:30:00,VEHICLE THEFT,INGLESIDE,-122.439044,37.716116,2015,47,23,16,2,...,0,1.0,0.126374,1.000000,0.0,0.501650,0.073484,2015-02-16,0,1
18366,2015-02-16 23:20:00,OTHER OFFENSES,INGLESIDE,-122.417141,37.739122,2015,47,23,16,2,...,0,1.0,0.126374,1.000000,0.0,0.648945,0.278714,2015-02-16,0,1
18367,2015-02-16 23:07:00,OTHER OFFENSES,RICHMOND,-122.465069,37.777185,2015,47,23,16,2,...,0,1.0,0.126374,1.000000,0.0,0.326640,0.618273,2015-02-16,0,1
18368,2015-02-16 23:00:00,LARCENY/THEFT,SOUTHERN,-122.397067,37.778752,2015,47,23,16,2,...,0,1.0,0.126374,1.000000,0.0,0.783939,0.632253,2015-02-16,0,1
18369,2015-02-16 23:00:00,LARCENY/THEFT,CENTRAL,-122.412514,37.799895,2015,47,23,16,2,...,0,1.0,0.126374,1.000000,0.0,0.680061,0.820868,2015-02-16,0,1
18370,2015-02-16 23:00:00,VEHICLE THEFT,BAYVIEW,-122.399482,37.722339,2015,47,23,16,2,...,0,1.0,0.126374,1.000000,0.0,0.767695,0.128999,2015-02-16,0,1
18371,2015-02-16 22:56:00,DRUG/NARCOTIC,MISSION,-122.410120,37.761761,2015,47,22,16,2,...,0,1.0,0.126374,0.956522,0.0,0.696159,0.480672,2015-02-16,0,1
18372,2015-02-16 22:56:00,WARRANTS,MISSION,-122.410120,37.761761,2015,47,22,16,2,...,0,1.0,0.126374,0.956522,0.0,0.696159,0.480672,2015-02-16,0,1
18373,2015-02-16 22:56:00,BURGLARY,MISSION,-122.410120,37.761761,2015,47,22,16,2,...,0,1.0,0.126374,0.956522,0.0,0.696159,0.480672,2015-02-16,0,1
18374,2015-02-16 22:56:00,STOLEN PROPERTY,MISSION,-122.410120,37.761761,2015,47,22,16,2,...,0,1.0,0.126374,0.956522,0.0,0.696159,0.480672,2015-02-16,0,1
18375,2015-02-16 22:52:00,WARRANTS,TENDERLOIN,-122.409524,37.785760,2015,47,22,16,2,...,0,1.0,0.126374,0.956522,0.0,0.700169,0.694770,2015-02-16,0,1
18376,2015-02-16 22:50:00,LARCENY/THEFT,CENTRAL,-122.406954,37.797177,2015,47,22,16,2,...,0,1.0,0.126374,0.956522,0.0,0.717447,0.796613,2015-02-16,0,1
18377,2015-02-16 22:45:00,VEHICLE THEFT,TENDERLOIN,-122.412971,37.785788,2015,47,22,16,2,...,0,1.0,0.126374,0.956522,0.0,0.676990,0.695021,2015-02-16,0,1
18378,2015-02-16 22:45:00,LARCENY/THEFT,NORTHERN,-122.429502,37.801184,2015,47,22,16,2,...,0,1.0,0.126374,0.956522,0.0,0.565818,0.832365,2015-02-16,0,1
18379,2015-02-16 22:38:00,OTHER OFFENSES,TARAVAL,-122.456060,37.714078,2015,47,22,16,2,...,0,1.0,0.126374,0.956522,0.0,0.387225,0.055302,2015-02-16,0,1
18380,2015-02-16 22:30:00,LARCENY/THEFT,CENTRAL,-122.407052,37.797655,2015,47,22,16,2,...,0,1.0,0.126374,0.956522,0.0,0.716788,0.800885,2015-02-16,0,1
18381,2015-02-16 22:19:00,WARRANTS,MISSION,-122.419672,37.765050,2015,47,22,16,2,...,0,1.0,0.126374,0.956522,0.0,0.631926,0.510017,2015-02-16,0,1
18382,2015-02-16 22:19:00,OTHER OFFENSES,MISSION,-122.419672,37.765050,2015,47,22,16,2,...,0,1.0,0.126374,0.956522,0.0,0.631926,0.510017,2015-02-16,0,1
18383,2015-02-16 22:19:00,OTHER OFFENSES,MISSION,-122.419672,37.765050,2015,47,22,16,2,...,0,1.0,0.126374,0.956522,0.0,0.631926,0.510017,2015-02-16,0,1
18384,2015-02-16 22:18:00,DRUG/NARCOTIC,MISSION,-122.410366,37.764311,2015,47,22,16,2,...,0,1.0,0.126374,0.956522,0.0,0.694508,0.503426,2015-02-16,0,1
18385,2015-02-16 22:18:00,DRUG/NARCOTIC,MISSION,-122.410366,37.764311,2015,47,22,16,2,...,0,1.0,0.126374,0.956522,0.0,0.694508,0.503426,2015-02-16,0,1
18386,2015-02-16 22:18:00,LIQUOR LAWS,MISSION,-122.410366,37.764311,2015,47,22,16,2,...,0,1.0,0.126374,0.956522,0.0,0.694508,0.503426,2015-02-16,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875103,2003-01-20 01:30:00,LARCENY/THEFT,NORTHERN,-122.433220,37.777489,2003,20,1,20,1,...,0,0.0,0.052198,0.043478,0.0,0.540815,0.620985,2003-01-20,0,1
875104,2003-01-20 01:29:00,ARSON,BAYVIEW,-122.387182,37.720967,2003,20,1,20,1,...,0,0.0,0.052198,0.043478,0.0,0.850414,0.116756,2003-01-20,0,1
875105,2003-01-20 01:25:00,OTHER OFFENSES,BAYVIEW,-122.387927,37.742703,2003,20,1,20,1,...,0,0.0,0.052198,0.043478,0.0,0.845399,0.310662,2003-01-20,0,1
875106,2003-01-20 01:16:00,VANDALISM,SOUTHERN,-122.402676,37.766716,2003,20,1,20,1,...,0,0.0,0.052198,0.043478,0.0,0.746220,0.524874,2003-01-20,0,1
875107,2003-01-20 01:01:00,WARRANTS,TENDERLOIN,-122.416262,37.785375,2003,20,1,20,1,...,0,0.0,0.052198,0.043478,0.0,0.654857,0.691334,2003-01-20,0,1
875108,2003-01-20 01:01:00,DRUG/NARCOTIC,TENDERLOIN,-122.416262,37.785375,2003,20,1,20,1,...,0,0.0,0.052198,0.043478,0.0,0.654857,0.691334,2003-01-20,0,1
875109,2003-01-20 01:00:00,VEHICLE THEFT,INGLESIDE,-122.407822,37.747129,2003,20,1,20,1,...,0,0.0,0.052198,0.043478,0.0,0.711612,0.350142,2003-01-20,0,1
875110,2003-01-20 01:00:00,NON-CRIMINAL,SOUTHERN,-122.394098,37.778994,2003,20,1,20,1,...,0,0.0,0.052198,0.043478,0.0,0.803905,0.634413,2003-01-20,0,1
875111,2003-01-20 00:50:00,VANDALISM,MISSION,-122.408805,37.763169,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.704999,0.493236,2003-01-20,0,1
875112,2003-01-20 00:40:00,OTHER OFFENSES,MISSION,-122.419658,37.764221,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.632016,0.502617,2003-01-20,0,1
875113,2003-01-20 00:40:00,DRUG/NARCOTIC,MISSION,-122.419658,37.764221,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.632016,0.502617,2003-01-20,0,1
875114,2003-01-20 00:30:00,OTHER OFFENSES,INGLESIDE,-122.427879,37.744484,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.576732,0.326547,2003-01-20,0,1
875115,2003-01-20 00:30:00,SUSPICIOUS OCC,INGLESIDE,-122.427879,37.744484,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.576732,0.326547,2003-01-20,0,1
875116,2003-01-20 00:24:00,ASSAULT,TENDERLOIN,-122.414744,37.778719,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.665065,0.631958,2003-01-20,0,1
875117,2003-01-20 00:20:00,ASSAULT,MISSION,-122.423623,37.764757,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.605358,0.507405,2003-01-20,0,1
875118,2003-01-20 00:05:00,OTHER OFFENSES,TARAVAL,-122.481183,37.743727,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.218278,0.319794,2003-01-20,0,1
875119,2003-01-20 00:02:00,DRUG/NARCOTIC,BAYVIEW,-122.387199,37.756779,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.850299,0.436231,2003-01-20,0,1
875120,2003-01-20 00:02:00,WARRANTS,BAYVIEW,-122.387199,37.756779,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.850299,0.436231,2003-01-20,0,1
875121,2003-01-20 00:01:00,VEHICLE THEFT,NORTHERN,-122.418065,37.786342,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.642731,0.699959,2003-01-20,0,1
875122,2003-01-20 00:01:00,VEHICLE THEFT,NORTHERN,-122.418065,37.786342,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.642731,0.699959,2003-01-20,0,1
875123,2003-01-20 00:01:00,FORGERY/COUNTERFEITING,MISSION,-122.430794,37.751557,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.557131,0.389651,2003-01-20,0,1
875124,2003-01-20 00:01:00,LARCENY/THEFT,SOUTHERN,-122.409629,37.772091,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.699460,0.572824,2003-01-20,0,1
875125,2003-01-20 00:01:00,ASSAULT,BAYVIEW,-122.378268,37.732381,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.910356,0.218577,2003-01-20,0,1
875126,2003-01-20 00:01:00,NON-CRIMINAL,TARAVAL,-122.501369,37.757800,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.082530,0.445337,2003-01-20,0,1
875127,2003-01-20 00:01:00,STOLEN PROPERTY,CENTRAL,-122.402212,37.791046,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.749341,0.741921,2003-01-20,0,1
875128,2003-01-20 00:01:00,FORGERY/COUNTERFEITING,SOUTHERN,-122.409629,37.772091,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.699460,0.572824,2003-01-20,0,1
875129,2003-01-20 00:01:00,OTHER OFFENSES,MISSION,-122.403532,37.753800,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.740460,0.409655,2003-01-20,0,1
875130,2003-01-20 00:01:00,VEHICLE THEFT,PARK,-122.444989,37.751778,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.461675,0.391619,2003-01-20,0,1
875131,2003-01-20 00:01:00,VEHICLE THEFT,PARK,-122.444989,37.751778,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.461675,0.391619,2003-01-20,0,1
875132,2003-01-20 00:01:00,FORGERY/COUNTERFEITING,INGLESIDE,-122.408363,37.711629,2003,20,0,20,1,...,0,0.0,0.052198,0.000000,0.0,0.707976,0.033452,2003-01-20,0,1

In [26]:
shdf[shdf['holidays'] == 1].shape

(28034, 21)

In [27]:
shdf.shape

(877982, 21)

In [ ]:
holidaysDF = shdf[['holidays','DateTime']]

In [ ]:
holidaysDF.head()

In [ ]:
holidaysDF.shape

In [ ]:
holidaysDF.to_csv('holidaysDF.csv', sep=',', index=False)